In [23]:
import pandas as pd
from astroquery.gaia import Gaia
from astropy.table import Table
import numpy as np

In [2]:
def clean_jobids():

    # Access to the Gaia Archive as registered user
    #Gaia.login()
    # Retrieve job's metadata - this may take a few minutes, depending on the number of jobs stored
    job_ids = [job.jobid for job in Gaia.list_async_jobs()]
    print('job ids',job_ids)
    # Gaia.list_async_jobs() method retrieves a "job" object that contains the job ID of each asynchronous job stored in the user account.
    # Uncomment the following line if you want to delete all the jobs stored in the user space and stop the code there. See below how to delete a subset of the jobs.
    Gaia.remove_jobs(job_ids)

In [10]:
def get_gaia_sample(catalog="gaiadr3.gold_sample_oba_stars"):
    """
    To grab the catalog star sample
    """

    query = "SELECT * FROM {}".format(catalog)

    job     = Gaia.launch_job_async(query,verbose=True)
    #job     = Gaia.launch_job(query)
    results = job.get_results()
    print(f'Table size (rows): {len(results)}')
    #results
    return results.to_pandas()

In [4]:
def clean_gaia_sample(targets):
    """
    Select OBA stars according to the pub A&A 674,A39 (2023) (Gaia Data Release 3: A golden sample of astrophysical parameters)
    """

    print(targets)

    # select as in paper
    idx = targets['vtan_flag'] == 0

    sel = targets[idx]

    print(len(targets),len(sel))

    return sel

In [5]:
def get_gaia_from_db(ra_min,ra_max,gaiadr='gaiadr3',catname='gaia_source'):
    # Main query, get selected infos with criteria.
    # All data information are given in the Gaia data model: 
    # https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_main_source_catalogue/ssec_dm_gaia_source.html

    vars = 'source_id, ra, dec, pmra, pmdec, parallax, parallax_error, phot_g_mean_mag, phot_bp_mean_mag, phot_rp_mean_mag, l, b, phot_variable_flag, ref_epoch'
    vars += ', L, B'
    
    if gaiadr == 'gaiadr2':
        vars += ', a_g_val'
    if gaiadr == 'gaiadr3':
        vars += ', ag_gspphot'

    """
    query = "SELECT {} \
    FROM {}.gaia_source \
    WHERE visibility_periods_used > 5 \
    AND astrometric_excess_noise < 0.5 \
    AND parallax > 1 \
    AND parallax_over_error > 5 \
    AND phot_bp_mean_flux_over_error > 20 \
    AND phot_rp_mean_flux_over_error > 20 \
    AND phot_g_mean_flux_over_error > 50 \
    AND phot_bp_rp_excess_factor < 1.2*(1.2+0.03*power(phot_bp_mean_mag-phot_rp_mean_mag,2)) \
    AND ra >= {} \
    and ra < {}".format(vars,gaiadr,ra_min,ra_max)
    """
    query = "SELECT {} \
    FROM {}.{} \
    WHERE visibility_periods_used > 8 \
    AND parallax_over_error > 10 \
    AND phot_bp_mean_flux_over_error > 20 \
    AND phot_rp_mean_flux_over_error > 20 \
    AND phot_g_mean_flux_over_error > 50 \
    AND phot_bp_rp_excess_factor < 1.3+0.06*power(phot_bp_mean_mag-phot_rp_mean_mag,2) \
    AND phot_bp_rp_excess_factor > 1.0+0.015*power(phot_bp_mean_mag-phot_rp_mean_mag,2) \
    AND astrometric_chi2_al/(astrometric_n_good_obs_al-5) < 1.44*greatest(1,exp(-0.4*(phot_g_mean_mag-19.5))) \
    AND ra >= {} \
    and ra < {}".format(vars,gaiadr,catname,ra_min,ra_max)    
    
    print(query)
    job     = Gaia.launch_job_async(query,verbose=True)
    #job     = Gaia.launch_job(query)
    results = job.get_results()
    print(f'Table size (rows): {len(results)}')
    results
    return results.to_pandas()

In [6]:
def get_sourceids(dr='gaiadr3',catalog='astrophysical_parameters'):

    vars = 'source_id'

    query = "SELECT {} FROM {}.{}".format(vars,dr,catalog)

    job     = Gaia.launch_job_async(query,verbose=True)
    #job     = Gaia.launch_job(query)
    results = job.get_results()
    print(f'Table size (rows): {len(results)}')
    results
    return results.to_pandas()

In [7]:
def get_gaia_from_dr(ra_min,ra_max,gaiadr='gaiadr3',catname='gaia_source'):
    """ 
    To get stars from a Gaia DR
    """
    
    tt = get_gaia_from_db(ra_min, ra_max,gaiadr,catname)
    ag = 'a_g_val'
    if gaiadr == 'gaiadr3':
        ag = 'ag_gspphot'
    # absolute mag G band - see Gaia Data Release 2 Documentation
    tt['MG'] = tt['phot_g_mean_mag']+5-5*np.log10(1.e3/tt['parallax'])-tt[ag]
    return tt

In [8]:
def get_targets(drs='gaiadr3',catname='gaia_source'):
    """
    To grab stars from the Gaia cat. The sky is splitted in RA slices to avoid memory pbs
    """
    
    ramin = 0
    ramax = 360
    delta_ra = 6
    ras = np.arange(ramin,ramax,delta_ra)
    outDir = '/home/philippe/LSST/gaia_files/{}/{}'.format(drs,catname)
    from sn_tools.sn_io import checkDir
    checkDir(outDir)
    for ra in ras:
        ra_min = np.round(ra,1)
        ra_max = np.round(ra_min+delta_ra,1)
        print(ra_min,ra_max)
        df = get_gaia_from_dr(ra_min,ra_max,drs,catname)
        out_name = '{}/sources_{}_{}.hdf5'.format(outDir,ra_min,ra_max)
        df.to_hdf(out_name,key='star')

In [9]:
def save_df(rr,drs,catname,key='oba_stars'):
    """
    To save a catalog
    """
    outDir = '/home/philippe/LSST/gaia_files/{}/{}'.format(drs,catname)
    from sn_tools.sn_io import checkDir
    checkDir(outDir)
    outName = 'sources_{}.hdf5'.format(catname)
    rr.to_hdf('{}/{}'.format(outDir,outName),key=key)

In [12]:
def get_oba_sources(catalog="gaiadr3.gold_sample_oba_stars"):
    tt_spl = table.split('.')
    drs = tt_spl[0]
    catname = tt_spl[1]
    rr = get_gaia_sample(catalog=catalog)
    save_df(rr,drs,catname,'oba_stars')

In [13]:
def get_fgkm_sources(catalog="gaiadr3.gold_sample_fgkm_stars"):
    tt_spl = table.split('.')
    drs = tt_spl[0]
    catname = tt_spl[1]
    rr = get_gaia_sample(catalog=catalog)
    tt = rr['evolstage_flame_spec'].unique()
    # some treatment to avoid Int32 pb...
    rr_cp = pd.DataFrame(rr)
    rr_cp["evolstage_flame_spec"] = rr_cp["evolstage_flame_spec"].apply(lambda x:-1 if x is pd.NA else x)
    #print(rr_cp['evolstage_flame_spec'].unique())
    rr_cp = rr_cp.fillna(int(-999))
    rr_cp["spectraltype_esphs"] = rr_cp["spectraltype_esphs"].apply(lambda x:'U' if x=='' else x)
    print(rr_cp['spectraltype_esphs'].unique())
    rr_cp['spectraltype_esphs'] = rr_cp['spectraltype_esphs'].astype(str)
    rr_cp['evolstage_flame'] = rr_cp['evolstage_flame'].astype(int)
    print(rr_cp.dtypes)
    save_df(rr_cp,drs,catname,'fgkm_stars')

In [31]:
def get_meta(df,Gaia,cols='ap.*'):
    
    table_id = Table([list(df['source_id'])], names=['gaia_id'], meta={'meta':'table'})
    Gaia.upload_table(upload_resource=table_id, table_name='tableid')

    query="SELECT {} \
    FROM gaiadr3.astrophysical_parameters AS ap \
    JOIN user_pgris.tableid as usert ON usert.gaia_id = ap.source_id".format(cols)

    #launch query and save and return a Dataframe
    job = Gaia.launch_job_async(query)
    results = job.get_results().to_pandas()

    # suggest delete your table from your personal space
    Gaia.delete_user_table(table_name='tableid')
    return results

In [34]:
Gaia.login(user='pgris', password='Lsst!!2024a=+')

INFO: Login to gaia TAP server [astroquery.gaia.core]
INFO: OK [astroquery.utils.tap.core]
INFO: Login to gaia data server [astroquery.gaia.core]
INFO: OK [astroquery.utils.tap.core]

In [34]:
#grab OBA catalog and save it on disk
# get_oba_sources()

Launched query: 'SELECT * FROM gaiadr3.gold_sample_oba_stars'
------>https
host = gea.esac.esa.int:443
context = /tap-server/tap/async
Content-type = application/x-www-form-urlencoded
303 303
[('Date', 'Tue, 21 Oct 2025 06:42:26 GMT'), ('Server', 'Apache/2.4.6 (SLES Expanded Support platform 7) OpenSSL/1.0.2k-fips mod_jk/1.2.43'), ('X-VO-Authenticated', 'pgris'), ('Location', 'https://gea.esac.esa.int/tap-server/tap/async/1761028946091O'), ('Cache-Control', 'no-cache, no-store, max-age=0, must-revalidate'), ('Pragma', 'no-cache'), ('Expires', '0'), ('X-XSS-Protection', '1; mode=block'), ('X-Frame-Options', 'SAMEORIGIN'), ('X-Content-Type-Options', 'nosniff'), ('Transfer-Encoding', 'chunked'), ('Content-Type', 'text/plain;charset=ISO-8859-1')]
job 1761028946091O, at: https://gea.esac.esa.int/tap-server/tap/async/1761028946091O
Retrieving async. results...
INFO: Query finished. [astroquery.utils.tap.core]
Table size (rows): 3023388

In [14]:
#grab FGKM stars and dump on disk
# get_fgkm_sources()

In [16]:
# get OBA source_id's
gaiaDir = '../../gaia_files'
gaiadr = 'gaiadr3'
oba_cat = 'gold_sample_oba_stars/sources_gold_sample_oba_stars.hdf5'

oba_stars = pd.read_hdf('{}/{}/{}'.format(gaiaDir,gaiadr,oba_cat))

oba_stars = clean_gaia_sample(oba_stars)
len(oba_stars)

                   source_id  vtan_flag
0         243212732278284416          0
1         243215068740428672          0
2         243222662242499840          0
3         243225651539759104          0
4         243225685899488640          0
...                      ...        ...
3023383  5959547056346917248          0
3023384  5959547567393419392          0
3023385  5959547670472310528          0
3023386  5959549255370331392          0
3023387  5959549392809229824          0

[3023388 rows x 2 columns]
3023388 2746935

2746935

In [19]:
oba_stars['source_id'].to_list()

[243212732278284416,
 243215068740428672,
 243222662242499840,
 243225651539759104,
 243225685899488640,
 243230461903072896,
 243232008091234816,
 243234481992427904,
 243236955893487616,
 243239395434866688,
 243241250861185408,
 243243827841075584,
 243245270950574336,
 243246507900622848,
 243248981801940096,
 243249806435630848,
 243257262499813632,
 243259633320654464,
 243262107221824384,
 243263447251579264,
 243268291975086336,
 243268841730865536,
 243270005662782976,
 243270181760227456,
 243272758740584448,
 243273480295064960,
 243274236209738496,
 243274889045633024,
 243275232642143744,
 243275713678442240,
 243281589193278080,
 243283994375039360,
 243289350195028608,
 243289968670451840,
 243292481230350080,
 243294267936710144,
 243302926591041792,
 243308561588092288,
 243308699027029632,
 243311344726854528,
 243313200152769536,
 243315536614919808,
 243315536614920448,
 243320411398938496,
 243322717801348096,
 243325432219353984,
 243325466579090688,
 243325569658309376,
 243326703529908736,
 243328284077621888,
 243329417949193728,
 243329589747880704,
 243331170295642752,
 243331616972238080,
 243332888282550528,
 243342509009828096,
 243343917759320064,
 243347731690249088,
 243348212726578560,
 243352438974110336,
 243352507693577728,
 243358486289010688,
 243359895037411200,
 243362953054102272,
 243363640248822528,
 243367076222682496,
 243367694698228608,
 243368210093993216,
 243369412684813696,
 243370164300808704,
 243371302470747392,
 243371439909711360,
 243372470701845760,
 243372608140800768,
 243378346217091840,
 243379269631092992,
 243380304722162560,
 243385046366032896,
 243386966213246976,
 5637655647047017216,
 243388722857737856,
 243390715722492288,
 243392227550938752,
 243393223983411968,
 243398618462226304,
 243399992851740416,
 243400748766427904,
 243401298518046080,
 243403566264505600,
 5637665508292930432,
 243403802484275840,
 243406555562115840,
 5637667329359020160,
 243407036598469888,
 243415523453740672,
 5637680695297227648,
 243415832691368064,
 243416141928991616,
 243424491345512064,
 5637683272277603456,
 243425247259709312,
 243428786312326016,
 243429645305779072,
 5637708865985187072,
 243429748386356608,
 243430504299622016,
 5637709557477132160,
 243432772042315648,
 5637721583385336192,
 243434799266793984,
 243435074144696064,
 5637724126006265600,
 243435211583692160,
 243439334752239360,
 5637742611545342976,
 243440812221053440,
 5637745016726979200,
 243442976884924032,
 5637746322397077504,
 243445450785696384,
 5637776558966681472,
 243447478010194816,
 243449230356806528,
 5637779307745673600,
 243450501667096448,
 5637784942742756352,
 243452150934502656,
 5637797552766767104,
 243454796634359040,
 5637799854869281664,
 5637816794220103808,
 243458610565465344,
 243463970684592128,
 5637827617537473920,
 243465516872738560,
 5637839540366853376,
 243468471810215296,
 243468540529693952,
 5637851703714180736,
 243469502602320256,
 5637864618677590528,
 243470808272373504,
 5637869742576471168,
 243471323669674240,
 243472010863241600,
 5637884414184911488,
 243472629338543872,
 243476679488451968,
 5637885303240089600,
 243477199184337920,
 5637888812231423744,
 243480532076314752,
 243484002412498304,
 5637897573964816640,
 243484410429827328,
 5637912726609229952,
 243485273722811776,
 5637929769039483136,
 243485376802014720,
 5637940381900668032,
 243489225092715008,
 243490599482912384,
 243494516492193792,
 5637971928438691712,
 243496337558560000,
 243496474997260032,
 5637991135532595456,
 243497471426436992,
 5637994056109991296,
 243500976122949120,
 243501319720340096,
 5638004020434179968,
 243501521579278464,
 5638005291744492672,
 243505064932054016,
 5638006803572969344,
 243512898952382336,
 243516850322299008,
 243519083705254016,
 243520458094776960,
 243522416599837568,
 243522446661366400,
 243523236935348224,
 243524100226986752,
 243525302817847680,
 243526161811318656,
 243528463913747456,
 243528635712562048,
 243530216260139008,
 243538359518418816,
 243540249304004480,
 243543169881347456,
 243545918660816512,
 243545918660816640,
 243547361769791104,
 243548564360589440,
 243556909477544960,
 243558356885883648,
 243558494324820224,
 243561071305722368,
 243561479324145408,
 243571276147520640,
 243572410018869376,
 243579346388082944,
 243580072240413824,
 243580450197546752,
 243580965593596288,
 243581545411355520,
 243581755867660928,
 243582576203501952,
 243585191841401216,
 243586115256548352,
 243586806749112960,
 243590105283925632,
 243591617112427136,
 243594915647296384,
 243594945709297280,
 243600275766546432,
 243602509149486592,
 243606460519360512,
 243608075427069952,
 243613195028030336,
 243613813503328768,
 243613950942277376,
 243616631003148928,
 243616837160993024,
 243619104903707648,
 243620307494540416,
 243621299627392256,
 243621819323041536,
 243622334719117184,
 243626384868863872,
 243629412825093248,
 243630821574399488,
 243631714927599360,
 243632986238067712,
 243638999192199936,
 243641816690679168,
 243641851050408832,
 243648860437010688,
 243649032236404224,
 243649650710970368,
 243650131747283712,
 243653739520556288,
 243654907751138560,
 243659271437631744,
 243663733904125184,
 243665043873659392,
 243666143385274496,
 243666590061853184,
 243669029603215232,
 243670300913664128,
 243670747590287744,
 243671434785015552,
 243672431217398016,
 243673358930325120,
 243673805606991232,
 243675454874392704,
 243677104141809280,
 243678856488758784,
 243680162158480384,
 243681880145364992,
 243690332640911104,
 243692050627832064,
 243692875261555584,
 243693734254985344,
 243694524528948992,
 243695967638302592,
 243698402880257664,
 243699369252017280,
 243700365684455552,
 243703492420601600,
 243705244767347840,
 243709780253329792,
 243710536167036672,
 243718194089541376,
 243725139056004992,
 243729674541445760,
 243731804845653248,
 243733797709992576,
 243737061885149440,
 243738264475963520,
 243738573713606016,
 243738711152573696,
 243738779872046976,
 243738848591522816,
 243740222980861056,
 243742353284609536,
 243746751331106176,
 243747747763515008,
 243750221664652288,
 243750530902570368,
 243752283248932864,
 243752691269215232,
 243752867364474112,
 243756028460404608,
 243756646935697408,
 243757265410976384,
 243759326997267072,
 243762075775828480,
 243763003488754048,
 243763862482192256,
 243768913363635584,
 243770906228502400,
 243771593423229824,
 243775166836125056,
 243775334335319168,
 243777327200139648,
 243777468938558592,
 243779186925432576,
 243783069575491072,
 243786402470424704,
 243787806920319872,
 243788395335292928,
 243795645239977216,
 243797706824301440,
 243802448468148096,
 243802826425253248,
 243803097002955264,
 243804544412093824,
 243805265966600064,
 243807293191589120,
 243810896664500864,
 243813271785704576,
 243814577455830144,
 243816432881662592,
 243817429314436992,
 243818150868550656,
 243819078581458560,
 243819520957891712,
 243820315532030592,
 243820590410715264,
 243820964066900608,
 243823854585057792,
 243825263334304896,
 243826534644586880,
 243830073697573760,
 243835743054380544,
 243839419546270976,
 243839522625503104,
 243839694424170368,
 243840278539743616,
 243840450338425344,
 243841962166930688,
 243843057379601536,
 243843611434347776,
 243844951465166848,
 243845363781163648,
 243847562804369408,
 243849658748340480,
 243851406796027776,
 243851582893719296,
 243851823412862208,
 243851926491107328,
 243852888564745728,
 243853644478598912,
 243855426885412096,
 243856702494646144,
 243856874293323392,
 5312225764581448576,
 5312226181212601216,
 5312226490450260608,
 5312226593529480192,
 5312226696608978944,
 5312226765328454784,
 5312226795373345152,
 5312226868411065472,
 5312226902767433600,
 5312227108925587968,
 5312227246364829312,
 5312227589961941760,
 5312227589961946240,
 5312227658681435776,
 5312227727400914560,
 5312227899199565952,
 5312227933559309440,
 5312228002278791808,
 5312228105357983232,
 5312228174077479808,
 5312228277156698240,
 5312228277156702464,
 5312228655113977472,
 5312228758193068288,
 5312228758193072640,
 5312228964351617408,
 5312229101790358400,
 5312229239229085696,
 5312229273589043584,
 5312229307948576000,
 5312229307948576512,
 5312229337994233856,
 5312229479747488256,
 5312229479751173760,
 5312229548466982912,
 5312229617186463744,
 5312229750311091200,
 5312229754625183360,
 5312229857704419456,
 5312229892064155136,
 5312229892064156800,
 5312229926423900928,
 5312230059547953792,
 5312230166942032512,
 5312230373100460032,
 5312230373100464640,
 5312230506224694656,
 5312230647978398464,
 5312230819777083264,
 5312230854136816896,
 5312230922856311680,
 5312231129014748416,
 5312231193420100480,
 5312231335173178496,
 5312232331605615872,
 5312232331605618048,
 5312232640843256704,
 5312232881361452800,
 5312233121879618048,
 5312233156239359232,
 5312233224958838272,
 5312233289363454976,
 5312233671635671296,
 5312233671635676928,
 5312233774714893824,
 5312233809078257024,
 5312233839128127360,
 5312233843434386176,
 5312233877794114432,
 5312233980873357696,
 5312234221391518336,
 5312234496269394944,
 5312234633708338176,
 5312234771147409280,
 5312234801192773376,
 5312234874226529024,
 5312235046025240960,
 5312235183464270336,
 5312235252183417600,
 5312235458342115968,
 5312235492701861248,
 5312235492701862272,
 5312235557107052928,
 5312235801939505024,
 5312235870658995968,
 5312235939378471168,
 5312236145536925696,
 5312236347380940672,
 5312236351695350016,
 5312236622260221824,
 5312236660933021824,
 5312236764012191488,
 5312236832731653248,
 5312237279408301568,
 5312237313768038400,
 5312237519926469888,
 5312237554285964032,
 5312237794804051200,
 5312238000962475648,
 5312238516362335872,
 5312238859955940992,
 5312239444071517568,
 5312239478431266560,
 5312239512790998912,
 5312239547150739968,
 5312239615870205056,
 5312239615870209024,
 5312239650229788288,
 5312240165626044544,
 5312240199985772032,
 5312240303065008640,
 5312240646662417920,
 5312240921540327936,
 5312241024619497728,
 5312241230777930496,
 5312241402576453760,
 5312241432623706368,
 5312241436936191232,
 5312241540019326976,
 5312241574375340032,
 5312241952332274048,
 5312241952332275072,
 5312242227212831232,
 5312242330293937408,
 5312242673889292160,
 5312242708249034112,
 5312242742608775168,
 5312242811328257920,
 5312242910087698176,
 5312242914407464832,
 5312242948767202304,
 5312243356761519360,
 5312243464162989440,
 5312243498522717056,
 5312243532882459776,
 5312243704681447680,
 5312243842120408576,
 5312243945199366912,
 5312243945199369600,
 5312243975233492096,
 5312244082638304768,
 5312244254437280128,
 5312244288797020672,
 5312244460595725184,
 5312244529315186560,
 5312244598034666624,
 5312244735473630848,
 5312244799867237248,
 5312244804193120000,
 5312244838552864000,
 5312244872914602496,
 5312244975991824640,
 5312245010351558784,
 5312245109104976256,
 5312245113430770048,
 5312245216509990784,
 5312245388308660224,
 5312245525747624192,
 5312245560107354752,
 5312245628826557952,
 5312245731905783936,
 5312245834985003776,
 5312246139896995200,
 5312246212942150912,
 243857561488086912,
 243858179963350912,
 243859726151641600,
 243860207187962496,
 243863230844941824,
 243863711881257472,
 243865429868144896,
 243865739106144128,
 243868762762769664,
 243869003280927616,
 243869656115928192,
 243869827915010304,
 243871167944767360,
 243871236663869696,
 243871614620980480,
 243873435687479040,
 243875634711185920,
 243878142971230848,
 243880067116543488,
 243881647664645504,
 243882884615182336,
 243882953334669568,
 243883709248877696,
 243883812328114816,
 243883949767431936,
 243888279094867200,
 243888485252507264,
 243889275526491264,
 243890615556255744,
 243891371470478848,
 243894876163805056,
 243896972107815040,
 243897831101251072,
 243898243419666816,
 243898896254694656,
 243899446010329984,
 243900545522131968,
 243901095277942272,
 243902366588251776,
 243903191221791872,
 243905802561887872,
 243906730274779776,
 243908310818907136,
 243911093961767040,
 243914495575530624,
 243915938684733056,
 243916007404207104,
 243917587952150400,
 243917656671624448,
 243917897189779968,
 243918687463729792,
 243918756183205248,
 243924528619223040,
 243924734777655040,
 243924734777658880,
 243926006087935232,
 243929545140956288,
 243930644652566272,
 243931194408357760,
 243931434926523904,
 243935317577294720,
 243936795046031232,
 243940368458811008,
 243942601841794944,
 243943941871570944,
 243944800865016192,
 243945453700048896,
 243946656290911104,
 243949469489281792,
 243949714307571328,
 243951329214997248,
 243951707172104192,
 243952497446086272,
 243953356439513216,
 243954318512164480,
 243955383664107776,
 243957548327565056,
 243957891924927616,
 243958613479446656,
 243958716558636800,
 243959781710954496,
 243961121740296832,
 243961156100029184,
 243961156100034304,
 243961637136348928,
 243962118173133184,
 243962942806385152,
 243963458202422656,
 243963698720583552,
 243964454634901120,
 243966138262021120,
 243969711675208960,
 243971601460741376,
 243972597893528448,
 243972804051560448,
 243973800484032512,
 243974487678330624,
 243977202097604480,
 243977648775067648,
 243979057523886080,
 243979882157580416,
 243980839930345728,
 243982562217190144,
 243982802735385472,
 243982974534054912,
 243983489930110080,
 243983764808003456,
 243985787732732160,
 243985792033093504,
 243985963831198208,
 243986616665965056,
 243987814957241472,
 243989399804744704,
 243989498584414848,
 243989502883945600,
 243990258798175360,
 243990293157911936,
 243991804986453120,
 243991869406397056,
 243992286022758400,
 243992831479068800,
 243993797851235840,
 243995893795227904,
 243995996874470400,
 243996409191318144,
 243996787148427264,
 243996787148428160,
 243998127178218752,
 243998814372962176,
 243999226689874304,
 243999467208023424,
 243999707726191616,
 243999776445665536,
 243999776445666688,
 244002697023395968,
 244003109340250496,
 244003452937626624,
 244004861687313408,
 244008228941650816,
 244008332020872448,
 244008675618225536,
 244008675618229760,
 244010702842743296,
 244012901865967872,
 244014757291779456,
 244015478841556224,
 244016058662220160,
 244016608422296832,
 244016921955332224,
 244017059395384064,
 244017402991642368,
 244017506070856576,
 244019258417471360,
 244020426648571776,
 244020976404369792,
 244021045124648576,
 244022213355090816,
 244022694391114624,
 244022861890421376,
 244023931341975040,
 244025649328611584,
 244025786767560064,
 244025889846779648,
 244026096005202816,
 244026710182912640,
 244029016584280320,
 244029360180319488,
 244030390972733440,
 244030768930980608,
 244031005148403328,
 244031834081703168,
 244032624355679360,
 244034887798836608,
 244035819811118720,
 244037739657714432,
 244038018834359680,
 244038431151213952,
 244038706029120384,
 244039874261497472,
 244040286578366592,
 244041660967880960,
 244042210723696768,
 244043138436618624,
 244046024654645632,
 244049976024521344,
 430701420693720960,
 430701558132674816,
 430701626852119168,
 430701626852283648,
 430702657644216960,
 430702863802604928,
 430703138680565120,
 430703241759790336,
 430703310479255040,
 430703413558435200,
 430703585357139712,
 430703585357155840,
 430703997674025472,
 430704169472655744,
 430704203832391680,
 430704409990806272,
 430704581789482624,
 430704719228406144,
 430704719228411904,
 430704753588138240,
 430704753588156544,
 430704787947863040,
 430704822307623040,
 430705268984338432,
 430705440782986880,
 430705509502471936,
 430705578221935616,
 430705612581643776,
 430705612581651968,
 430705681301160704,
 430705921819308800,
 430706265416693888,
 430706299776409472,
 430706299776420608,
 430706402855604992,
 430706535991505920,
 430706604711105280,
 430706746452979712,
 430706883891912960,
 430706918251626240,
 430707021330862464,
 430707090050320896,
 430707120107457024,
 430707227489233280,
 430707227489237760,
 430707330568542336,
 430707429344903168,
 430707468007458048,
 430707536726923264,
 430707536726933760,
 430707742885341696,
 430707742885345536,
 430707807300009984,
 430707845964578176,
 430708292641101056,
 430708498799546368,
 430708498799553152,
 430708704957962496,
 430708735021974400,
 430708739317697152,
 430708911116351232,
 430708911116365696,
 430709185994249728,
 430709559646679040,
 430709804469872512,
 430709834524583680,
 430710148067213056,
 430710281201180032,
 430710285506116736,
 430710629103534592,
 430710663463281280,
 430710830958366720,
 430710972700875264,
 430711350657950848,
 430711762974849920,
 430711934773511424,
 430711934773511552,
 430711964829787776,
 430712106572201344,
 430712136630941952,
 430712209651379072,
 430712244011156352,
 430712244011163264,
 430712244011172736,
 430712312730610816,
 430712450169536128,
 430712931205874048,
 430713064339984896,
 430713996357798272,
 430714030717550720,
 430714030717558656,
 430715027149626496,
 430715473826216064,
 430715473826216192,
 430715714344591488,
 430716332819884544,
 430716676417250816,
 430716676420254080,
 430716779496935424,
 430716848215906688,
 430716848215912576,
 430717363611978368,
 430717569770243456,
 430717810288550016,
 430717947727488384,
 430718119526053120,
 430718153885900160,
 430718188245633280,
 430718841080815360,
 430719047239202304,
 430719047239215360,
 430719150318416128,
 430719253397625088,
 430719283452623488,
 430719356476812160,
 430719558333010048,
 430719665714485120,
 430719901927913472,
 430720181110491136,
 430720249829983744,
 430720352909183488,
 430720421628658176,
 430720627787138816,
 430720833945542144,
 430720833945553920,
 430720833946064384,
 430720833946065280,
 430721108823446784,
 430721143183161472,
 430721555499980160,
 430721933457127424,
 430722036536324736,
 430722070896063232,
 430722173975272192,
 430722173975277184,
 430722173975283200,
 430722173975286400,
 430722380136644608,
 430722551932977152,
 430722826810355200,
 430722929889558400,
 430722998609037696,
 430722998609040256,
 430723170407703680,
 430723273486929536,
 430723617084284160,
 430723926321937664,
 430724201199824896,
 430724201199825664,
 430724476077723520,
 430725060193280896,
 430725128912756224,
 430725330769799680,
 430725369430914048,
 430725403790640512,
 430725438150395008,
 430725781747757440,
 430725919186706560,
 430726125345148160,
 430726189763303680,
 430726468942514944,
 430726503302249728,
 430726537661996672,
 430726675100946688,
 430726881259369216,
 430726881262344576,
 430726949978846208,
 430727121779200384,
 430727121779200768,
 430727151832100224,
 430727362297367936,
 430727396657104128,
 430727499736317056,
 430727980772647296,
 430728736686883712,
 430728908485565952,
 430729247776739840,
 430729252082930944,
 430729488294909184,
 430729630040070272,
 430729664399806208,
 430730106770198272,
 430730248515346560,
 430730523393255424,
 5638533430985082112,
 5638533538369832960,
 5638533847607379328,
 5638533881967144448,
 5638534225564631424,
 5638534809680090624,
 5638534844039863936,
 5638534947119012608,
 5638534947119024896,
 5638535050198294784,
 5638535359435837440,
 5638535737392947200,
 5638536012270807680,
 5638536252788985344,
 5638536527666943488,
 5638536733825388928,
 5638536871264127744,
 5638537210558618624,
 5638537524099519872,
 5638537588514993792,
 5638537867696606848,
 5638538039484647040,
 5638538039495286784,
 5638538142574498176,
 5638538142574499072,
 5638538280013438720,
 5638538348732926080,
 5638538692330327808,
 5638539310805590272,
 5638539516964668288,
 5638540066719817728,
 5638540204158760320,
 5638540341597693952,
 5638540547756123392,
 5638540650835332224,
 5638540856993797888,
 5638541028792480128,
 5638541715987235712,
 5638541784706694912,
 5638542884219831808,
 5638543051713238272,
 5638543262176976896,
 5638543330896482304,
 5638543537054890496,
 5638543571414614016,
 5638543635827368960,
 5638543674493819904,
 5638543674493824128,

In [24]:
# make a request to grab available columns
rr = get_meta(oba_stars[:10],Gaia)
cols = rr.columns.to_list()
cols = list(filter(lambda s: not ('oa' in s), cols))
cols_db = ','.join(cols)
cols_db

INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]

,solution_id,source_id,classprob_dsc_combmod_quasar,classprob_dsc_combmod_galaxy,classprob_dsc_combmod_star,classprob_dsc_combmod_whitedwarf,classprob_dsc_combmod_binarystar,classprob_dsc_specmod_quasar,classprob_dsc_specmod_galaxy,classprob_dsc_specmod_star,...,ag_msc_upper,ag_msc_lower,logposterior_msc,mcmcaccept_msc,mcmcdrift_msc,flags_msc,neuron_oa_id,neuron_oa_dist,neuron_oa_dist_percentile_rank,flags_oa
0,1636148068921376768,243212732278284416,1.022396e-13,5.106816e-13,0.999979,5.342136e-10,0.000021,0.000000,0.0,0.997854,...,0.444588,0.122586,-176.645203,0.174511,0.067618,0,<NA>,NaN,<NA>,
1,1636148068921376768,243215068740428672,5.124280e-11,5.103790e-13,0.999985,2.387608e-10,0.000015,0.000005,0.0,0.998451,...,5.000000,0.000000,-698.042114,0.131050,0.010333,0,<NA>,NaN,<NA>,
2,1636148068921376768,243222662242499840,2.685261e-11,5.104969e-13,0.999982,3.322484e-10,0.000018,0.000003,0.0,0.998218,...,1.968054,0.506835,-334.070557,0.115704,0.016557,0,<NA>,NaN,<NA>,
3,1636148068921376768,243225651539759104,1.023207e-13,5.110869e-13,0.999970,8.197416e-10,0.000030,0.000000,0.0,0.997054,...,0.956783,0.493951,-1213.568848,0.168067,0.059471,1,<NA>,NaN,<NA>,
4,1636148068921376768,243225685899488640,1.200140e-10,5.122913e-13,0.999947,9.994340e-09,0.000053,0.000012,0.0,0.994687,...,0.241910,0.000000,-977.054382,0.199928,0.046965,0,<NA>,NaN,<NA>,
5,1636148068921376768,243230461903072896,1.022697e-13,5.108319e-13,0.999976,5.619797e-10,0.000024,0.000000,0.0,0.997557,...,2.100900,0.204877,-4772.345215,0.156778,0.052380,1,<NA>,NaN,<NA>,
6,1636148068921376768,243232008091234816,6.965268e-11,5.110064e-13,0.999972,2.148561e-09,0.000028,0.000007,0.0,0.997213,...,0.558281,0.511669,-3695.009766,0.236874,0.763130,1,<NA>,NaN,<NA>,
7,1636148068921376768,243234481992427904,6.058117e-11,5.107268e-13,0.999978,1.028625e-09,0.000022,0.000006,0.0,0.997765,...,0.744663,0.000000,-5678.925293,0.174702,0.022446,1,<NA>,NaN,<NA>,
8,1636148068921376768,243236955893487616,1.024326e-13,5.116459e-13,0.999967,1.583095e-07,0.000033,0.000000,0.0,0.995962,...,0.813045,0.000000,-2377.143555,0.185107,0.017585,1,<NA>,NaN,<NA>,
9,1636148068921376768,243239395434866688,1.022781e-13,5.108740e-13,0.999975,4.727441e-10,0.000025,0.000000,0.0,0.997474,...,1.605500,0.469493,-1703.919922,0.129690,0.035880,1,<NA>,NaN,<NA>,

In [36]:
arr_spl = np.array_split(oba_stars, 20)
df_fi = pd.DataFrame()
clean_jobids()
Gaia.delete_user_table(table_name='tableid')
for i,vv in enumerate(arr_spl):
    print(i,len(vv))
    dfb = get_meta(vv,Gaia,cols_db)
    df_fi = pd.concat((df_fi,dfb))
df_fi

/home/philippe/anaconda3/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

job ids []
INFO: Removed jobs: '[]'. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
0 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
1 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
2 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
3 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
4 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
5 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
6 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
7 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
8 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
9 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
10 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
11 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
12 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
13 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
14 137347
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
15 137346
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
16 137346
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
17 137346
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
18 137346
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]
19 137346
INFO: Sending pytable. [astroquery.utils.tap.core]
INFO: Uploaded table 'tableid'. [astroquery.utils.tap.core]

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.generic]

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Table 'tableid' deleted. [astroquery.utils.tap.core]

,solution_id,source_id,classprob_dsc_combmod_quasar,classprob_dsc_combmod_galaxy,classprob_dsc_combmod_star,classprob_dsc_combmod_whitedwarf,classprob_dsc_combmod_binarystar,classprob_dsc_specmod_quasar,classprob_dsc_specmod_galaxy,classprob_dsc_specmod_star,...,logg_msc2,logg_msc2_upper,logg_msc2_lower,ag_msc,ag_msc_upper,ag_msc_lower,logposterior_msc,mcmcaccept_msc,mcmcdrift_msc,flags_msc
0,1636148068921376768,243212732278284416,1.022396e-13,5.106816e-13,0.999979,5.342136e-10,0.000021,0.000000,0.000000,0.997854,...,4.197229,4.721307,4.105352,0.361903,0.444588,0.122586,-176.645203,0.174511,0.067618,0
1,1636148068921376768,243215068740428672,5.124280e-11,5.103790e-13,0.999985,2.387608e-10,0.000015,0.000005,0.000000,0.998451,...,3.874521,5.200000,2.000000,0.882090,5.000000,0.000000,-698.042114,0.131050,0.010333,0
2,1636148068921376768,243222662242499840,2.685261e-11,5.104969e-13,0.999982,3.322484e-10,0.000018,0.000003,0.000000,0.998218,...,3.949830,5.025512,3.432509,1.242911,1.968054,0.506835,-334.070557,0.115704,0.016557,0
3,1636148068921376768,243225651539759104,1.023207e-13,5.110869e-13,0.999970,8.197416e-10,0.000030,0.000000,0.000000,0.997054,...,4.159162,4.915750,3.717377,0.624483,0.956783,0.493951,-1213.568848,0.168067,0.059471,1
4,1636148068921376768,243225685899488640,1.200140e-10,5.122913e-13,0.999947,9.994340e-09,0.000053,0.000012,0.000000,0.994687,...,3.951599,4.821571,3.581628,0.076618,0.241910,0.000000,-977.054382,0.199928,0.046965,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137341,1636148068921376768,5959547056346917248,1.020557e-13,5.097633e-13,0.999997,2.003229e-12,0.000003,0.000000,0.000000,0.999669,...,4.266311,4.423877,4.109059,0.315463,0.329963,0.291800,-2549.920410,0.266874,0.704024,1
137342,1636148068921376768,5959547567393419392,1.020413e-13,5.096971e-13,0.999998,2.002944e-12,0.000002,0.000000,0.000000,0.999813,...,5.049195,5.200000,4.324937,0.938304,1.118404,0.813499,-662.849121,0.284200,0.229424,0
137343,1636148068921376768,5959547670472310528,1.512998e-10,5.106537e-13,0.999979,1.215285e-09,0.000021,0.000015,0.000000,0.997909,...,3.561956,5.200000,3.261623,0.174846,1.901548,0.000000,-9456.500000,0.155943,0.037604,1
137344,1636148068921376768,5959549255370331392,1.020397e-13,6.026252e-11,0.999998,2.002910e-12,0.000002,0.000000,0.000001,0.999830,...,5.004127,5.200000,3.441970,1.119420,1.566388,0.585613,-51.275024,0.235227,0.107411,0
137345,1636148068921376768,5959549392809229824,1.021034e-13,5.100015e-13,0.999992,2.703286e-10,0.000008,0.000000,0.000000,0.999198,...,4.096786,4.162528,4.040600,0.233903,0.290077,0.164525,-2110.125488,0.253508,0.427806,1

In [50]:
#df_fi['evolstage_flame'] = df_fi['evolstage_flame'].astype(int)
#df_fi["evolstage_flame_spec"] = df_fi["evolstage_flame_spec"].apply(lambda x:-1 if x is pd.NA else x)
#print(rr_cp['evolstage_flame_spec'].unique())
df_fi = df_fi.fillna(int(-999))
df_fi["spectraltype_esphs"] = df_fi["spectraltype_esphs"].apply(lambda x:'U' if x=='' else x)
#print(rr_cp['spectraltype_esphs'].unique())
df_fi['spectraltype_esphs'] = df_fi['spectraltype_esphs'].astype(str)
for vv in df_fi.dtypes:
    print(type(vv))
#save_df(df_fi,'gaiadr3','golden_sample_oba_astrophysical_parameters')

<class 'numpy.dtypes.Int64DType'>
<class 'numpy.dtypes.Int64DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>
<class 'pandas.core.arrays.integer.Int32Dtype'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.Float32DType'>
<class 'numpy.dtypes.ObjectDType'>

In [14]:
targets

,source_id,ra,dec,pmra,pmdec,parallax,parallax_error,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,l,b,phot_variable_flag,ref_epoch,L,B,ag_gspphot,MG
12,423289063054369024,0.400430,59.672497,-4.377066,-1.054522,0.457445,0.020055,14.929647,15.329857,14.351916,116.671442,-2.592115,NOT_AVAILABLE,2016.0,116.671442,-2.592115,1.3218,1.909540
36,423289509730936576,0.364285,59.702281,-1.777071,-0.541931,0.333426,0.012067,13.022193,13.334257,12.532269,116.659260,-2.559376,NOT_AVAILABLE,2016.0,116.659260,-2.559376,NaN,NaN
44,423289681529592704,0.345458,59.742632,-3.021024,-2.500900,0.348504,0.014043,14.087346,14.365150,13.647771,116.657728,-2.517951,NOT_AVAILABLE,2016.0,116.657728,-2.517951,1.0354,0.762985
46,423289681529603328,0.377291,59.734461,-2.464894,-1.957056,0.286316,0.012006,12.733460,12.903208,12.425391,116.671907,-2.529062,NOT_AVAILABLE,2016.0,116.671907,-2.529062,1.2705,-1.252813
49,423289715889351808,0.324619,59.714754,-2.017454,-1.542614,0.319811,0.021189,15.105708,15.504957,14.505490,116.642019,-2.543275,NOT_AVAILABLE,2016.0,116.642019,-2.543275,1.8370,0.793179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896811,1997464292947011328,354.039307,55.493297,2.533718,0.973578,0.408756,0.022502,15.054265,15.326829,14.619435,112.346496,-5.823654,NOT_AVAILABLE,2016.0,112.346496,-5.823654,0.7712,2.340383
896870,1997468175597382016,354.161792,55.596995,-1.126363,-0.618143,0.726699,0.016450,13.568130,13.862082,13.105453,112.443188,-5.744274,NOT_AVAILABLE,2016.0,112.443188,-5.744274,0.8300,2.044904
896938,1997481163578395264,354.102056,55.665601,-2.625141,-2.146707,0.456080,0.020978,15.021451,15.351855,14.516724,112.430525,-5.668873,NOT_AVAILABLE,2016.0,112.430525,-5.668873,1.3510,1.965656
896987,1997485802142965248,354.047289,55.765659,2.938829,-2.523933,1.237782,0.013845,11.613557,11.811242,11.278930,112.429792,-5.564170,NOT_AVAILABLE,2016.0,112.429792,-5.564170,0.5411,1.535677
897007,1997486729856248448,354.072023,55.817821,-0.600322,-1.652350,0.442730,0.013476,13.685146,13.951657,13.264149,112.458271,-5.518228,NOT_AVAILABLE,2016.0,112.458271,-5.518228,0.7705,1.145339

In [15]:
targets.to_hdf('targets_OBA.hdf5',key='gaiadr3')

In [16]:
sel.to_hdf('OBA_gloden.hdf5',key='gaiadr3')